### ISSUE TITLE
upgrade LTS jdk version 11 (or better 17)

### ISSUE THREAD

**Issue by jangalinski** [toolisticon/FluApiGen#20]
I noticed this project is set up for java 1.8 ... which reached EOL a while ago. We should switch to v17 (or at least v11).

**Comment by tobiasstamann** [comment]
The project itself can be build and is functional with all java versions >= 8. 
I would like to keep Java 8 code compatibility to ensure maximal compatibility for the moment, because some Java 8 distributions have not reached EOL at the moment. 

So it would be ok for me to go for java 11 or 17 for releases and keep 1.8 source code compatibility.
